Fix: Sony Channels to Viasat ones
iptv-org/epg pull request #1370
Opened 2022-11-20 13:54 UTC by smrtprjcts

Hi @freearhey,
Maybe  xmltv_ids should be modified, I don't know.
Thanks

2022-11-20 15:34 UTC, freearhey requested changes
For everything to work correctly it is necessary to update not only the channel name and `xmltv_id` but also the `site_id` if it has changed.

2022-11-20 15:35 UTC, freearhey commented on sites/musor.tv/musor.tv_hu.channels.xml
> +    <channel lang="hu" xmltv_id="SonyMaxHungary.hu" site_id="SONY_MAX">Viasat2</channel>
```suggestion
    <channel lang="hu" xmltv_id="Viasat2.hu" site_id="VIASAT2">Viasat2</channel>
```

2022-11-20 15:35 UTC, freearhey commented on sites/musor.tv/musor.tv_hu.channels.xml
> +    <channel lang="hu" xmltv_id="SonyMovieChannelHungary.hu" site_id="SONY_MOVIE_CHANNEL">Viasat Film</channel>
```suggestion
    <channel lang="hu" xmltv_id="ViasatFilm.hu" site_id="VIASAT_FILM">Viasat Film</channel>
```

2022-11-20 17:43 UTC, smrtprjcts commented
Fix them

2022-11-21 03:48 UTC, freearhey approved these changes

2022-11-21 03:48 UTC, merged