Update tv24.se.channels.xml
iptv-org/epg pull request #1950
Opened 2023-02-02 16:48 UTC by Smark223

Add NRK Super/NRK3 combined guide.

2023-02-02 16:49 UTC, freearhey requested changes

2023-02-02 16:49 UTC, freearhey commented on sites/tv24.se/tv24.se.channels.xml
> +    <channel lang="sv" xmltv_id="NRK3NRKSuper.no" site_id="/nrk-super-nrk3-hd">NRK Super/NRK3</channel>
```suggestion
    <channel lang="sv" xmltv_id="NRK3NRKSuper.no" site_id="nrk-super-nrk3-hd">NRK Super/NRK3</channel>
```

2023-02-02 21:51 UTC, freearhey approved these changes

2023-02-03 15:02 UTC, ajanes3 approved these changes

2023-02-03 15:09 UTC, merged