Update sky.com.channels.xml
iptv-org/epg pull request #1969
Opened 2023-02-06 11:14 UTC by Smark223

Add Premier Sports 1 and 2

2023-02-06 11:28 UTC, RevGear commented
Premier Sports 1 and 2 don't exist anymore. They were rebranded as ViaPlay Sport 1 and 2 last year. Some of their coverage still includes the Premier Sports logo, especially the older footage.

2023-02-06 12:22 UTC, Smark223 commented
They do exist in Ireland https://www.nowtv.com/ie/sports-overview# however, I think you're right in that the site IDs I've used in this amendment are the ones for the old UK Premier Sports channels that are indeed defunct, so this probably needs rejecting. Can someone check?

2023-02-06 13:09 UTC, Smark223 commented
> I hadn't realised they were still using Premier Sports branding in Ireland. According to Wikipedia, the Irish feed has reverted back to Premier Sports with a slightly different schedule.
> 
> > Viaplay rebranded Premier Sports under the Viaplay Sports name on 1 November 2022. Initially, the same feeds were used for the UK and Ireland with Premier Sports branding used for Premier League coverage which is blocked in the UK. On 28 November the channels split, with the Irish feeds reverting to full Premier Sports branding.
> 
> Maybe we need two new IDs for PremierSportsIreland1.ie and PremierSportsIreland2.ie as these are effectively new channels.

@freearhey created them in the database earlier under https://github.com/iptv-org/database/commit/ef79ea7d0faefc1011cb5fe8afb58ee65f3d7545 but as PremierSports1.ie and PremierSports2.ie

2023-02-06 13:17 UTC, Smark223 commented
Anyway, I think I've messed up with this request. I'm not able to check if those site IDs are correct at the moment but I would expect the schedules for the Premier Sports channels to be included on the Sky site. I can't get it to show me Irish channels though, even with a VPN.

2023-02-06 13:57 UTC, RevGear commented
> @freearhey created them in the database earlier under [iptv-org/database@ef79ea7](https://github.com/iptv-org/database/commit/ef79ea7d0faefc1011cb5fe8afb58ee65f3d7545) but as PremierSports1.ie and PremierSports2.ie Not sure if the 'Ireland' is needed in the ID - unsure what the standard is. It seems when there are multiple versions of a channel with the same name in different countries, sometimes a country suffix is added to the ID but sometime it's not.

I thought PremierSports1.ie and PremierSports2.ie were already in the database, as the original channels prior to ViaPlay branding. Maybe they got deleted instead of marked as closed. I suggested using 'Ireland' to avoid confusion with the closed channels, but maybe that's not necessary.

2023-02-07 00:00 UTC, freearhey commented
I added a country suffix to the channel name: https://github.com/iptv-org/database/commit/02d856414ff6a2b3c3d82e72d432fe44f56758db

2023-02-07 00:01 UTC, freearhey requested changes

2023-02-07 00:01 UTC, freearhey commented on sites/sky.com/sky.com.channels.xml
> +    <channel lang="en" xmltv_id="PremierSports2.ie" site_id="1635">Premier Sports 2</channel>
```suggestion
    <channel lang="en" xmltv_id="PremierSports1Ireland.ie" site_id="1633">Premier Sports 1 Ireland</channel>
    <channel lang="en" xmltv_id="PremierSports2Ireland.ie" site_id="1635">Premier Sports 2 Ireland</channel>
```

2023-02-09 00:40 UTC, freearhey approved these changes

2023-02-09 01:11 UTC, PopeyeTheSai10r approved these changes

2023-02-09 01:14 UTC, merged