Se agregó un nuevo proveedor 'claro.com.br', tener en cuenta que se n…
iptv-org/epg pull request #2355
Opened 2024-04-16 22:44 UTC by mhmorales

…ecesita tener la vpn de nimbus para poder usarlo correctamente. En el archivo xml de los channels está armado para obtener la programación de los canales correspondientes a la ciudad de Sao Paulo que corresponde al id 1.

2024-04-16 22:45 UTC, mhmorales reviewed
Claro BR es a new site

2024-04-20 06:14 UTC, andreisergeevic approved these changes

2024-04-20 12:25 UTC, BellezaEmporium reviewed
If I understand well :

- City ID is just the 1 (I suppose either Sao Paulo (the economic capital) or Brasilia (the politcal capital)), channel ID is "1_xxxx" (depending on the channel in the XML).

This would mean Claro Brasil takes multiple cities into account ?

2024-06-17 11:52 UTC, BellezaEmporium approved these changes

2024-06-22 13:02 UTC, freearhey requested changes
I'm getting a 500 error:

```sh
npm run grab -- --site=claro.com.br

> grab
> npx tsx scripts/commands/epg/grab.ts --site=claro.com.br

starting...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: claro.com.br
loading channels...
  found 245 channel(s)
run #1:
  [1/490] claro.com.br (pt) - Canal2.br - Jun 22, 2024 (0 programs)
    ERR: Request failed with status code 500
```

2024-06-29 14:05 UTC, PopeyeTheSai10r commented
Everything returns 0 program

<details>
<summary>Output</summary>

  ```
[1/490] claro.com.br (pt) - Canal2.br - Jun 29, 2024 (0 programs)
  [2/490] claro.com.br (pt) - Canal2.br - Jun 30, 2024 (0 programs)
  [3/490] claro.com.br (pt) - TVCamara.br - Jun 30, 2024 (0 programs)
  [4/490] claro.com.br (pt) - TVJustica.br - Jun 30, 2024 (0 programs)
  [5/490] claro.com.br (pt) - TVSenado.br - Jun 30, 2024 (0 programs)
  [6/490] claro.com.br (pt) - RedeTV.br - Jun 30, 2024 (0 programs)
  [7/490] claro.com.br (pt) - Viva.br - Jun 30, 2024 (0 programs)
  [8/490] claro.com.br (pt) - Viva.br - Jun 29, 2024 (0 programs)
  [9/490] claro.com.br (pt) - RedeTV.br - Jun 29, 2024 (0 programs)
  [10/490] claro.com.br (pt) - Multishow.br - Jun 30, 2024 (0 programs)
  [11/490] claro.com.br (pt) - Multishow.br - Jun 29, 2024 (0 programs)
  [12/490] claro.com.br (pt) - TVSenado.br - Jun 29, 2024 (0 programs)
  [13/490] claro.com.br (pt) - Record.br - Jun 30, 2024 (0 programs)
  [14/490] claro.com.br (pt) - GNT.br - Jun 30, 2024 (0 programs)
  [15/490] claro.com.br (pt) - GNT.br - Jun 29, 2024 (0 programs)
```
</details>

2024-09-07 18:45 UTC, closed without merging