Fix mewatch.sg
iptv-org/epg pull request #2425
Opened 2024-09-03 17:38 UTC by harunmahfud

Changes in this PR:

- Fix error getting channel list when processing `https://www.mewatch.sg/paris2024/epg`.
- Dynamically set the date-time parameter to retrieve EPG list, so it always grabs a full day's schedule no matter what timezone the client's in.
- Updated the `channels.xml` file with the latest version from Mewatch.

2024-09-07 18:26 UTC, freearhey requested changes
Test failed:

```sh
npm test -- mewatch.sg

> test
> run-script-os mewatch.sg


> test:default
> TZ=Pacific/Nauru npx jest --runInBand mewatch.sg

 FAIL  sites/mewatch.sg/mewatch.sg.test.js
  ✕ can generate valid url (35 ms)
  ✓ can parse response (2 ms)
  ✓ can handle empty guide

  ● can generate valid url

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://cdn.mewatch.sg/api/schedules?channels=97098&date=2022-06-11&duration=24&ff=idp,ldp,rpt,cd&hour=21&intersect=true&lang=en&segments=all"
    Received: "https://cdn.mewatch.sg/api/schedules?channels=97098&date=2022-06-10&duration=24&ff=idp,ldp,rpt,cd&hour=12&intersect=true&lang=en&segments=all"

      13 |
      14 | it('can generate valid url', () => {
    > 15 |   expect(url({ channel, date })).toBe(
         |                                  ^
      16 |     'https://cdn.mewatch.sg/api/schedules?channels=97098&date=2022-06-11&duration=24&ff=idp,ldp,rpt,cd&hour=21&intersect=true&lang=en&segments=all'
      17 |   )
      18 | })

      at Object.<anonymous> (sites/mewatch.sg/mewatch.sg.test.js:15:34)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        3.581 s
Ran all test suites matching /mewatch.sg/i.
```

2024-09-08 00:14 UTC, harunmahfud commented
Since the default timezone used in test is [`Pasific/Nauru`](https://github.com/iptv-org/epg/blob/master/package.json#L16) (GMT+12), I've updated the `hour` param for expected test URL to `12` (https://github.com/iptv-org/epg/pull/2425/commits/e7335a8662223d87dd11f58a0a252b0bda31ee58)

2024-09-22 19:32 UTC, freearhey approved these changes

2024-09-28 01:53 UTC, PopeyeTheSai10r approved these changes

2024-09-28 01:53 UTC, merged