Update tv.yandex.ru guide.
iptv-org/epg pull request #2481
Opened 2024-11-26 14:36 UTC by tohenk

```sh
npm run grab -- --site=tv.yandex.ru

> grab
> npx tsx scripts/commands/epg/grab.ts --site=tv.yandex.ru

starting...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: tv.yandex.ru
loading channels...
  found 1 channel(s)
run #1:
  [1/1] tv.yandex.ru (ru) - 3ABNRussia.ru - Nov 26, 2024 (86 programs)
  saving to "guide.xml"...
  done in 00h 01m 22s
```

Close #2451

2024-11-30 14:46 UTC, freearhey requested changes
Test failed:

```sh
npm test -- tv.yandex.ru                   

> test
> run-script-os tv.yandex.ru


> test:default
> TZ=Pacific/Nauru npx jest --runInBand tv.yandex.ru

 FAIL  sites/tv.yandex.ru/tv.yandex.ru.test.js (13.17 s)
  ✓ can generate valid url (7 ms)
  ✕ can generate valid request headers (9 ms)
  ✕ can parse response (10004 ms)
  ✓ can handle empty guide (1 ms)

  ● can generate valid request headers

    expect(received).toMatchObject(expected)

    - Expected  - 1
    + Received  + 1

      Object {
    -   "Cookie": "i=dkim62pClrWWC4CShVQYMpVw1ELNVw4XJdL/lzT4E2r05IgcST1GtCA4ho/UyGgW2AO4qftDfZzGX2OHqCzwY7GUkpM=; spravka=dD0xNzMyMzg1MjQ4O2k9MTgwLjI0Ny4yNDEuNzA7RD1DMjQ4OTYzRURBNEE1NjVEMjg0Rjc5MDQyNEYzMjdGRDVERTg0MkQ2ODBCOUNCREUwQjk4OEYzRThDREIwQjVBNTUwRjc1OTFCRkMwRTRBRTM3RDA4MjZCMDAyNzhDMjEwMUYzOTE0NEQ5NjhBNjJGNENDRTYwM0ZDQUY4QjBBRTA0NDRGNjNENTQ0OUQ5MzkxMTdFRTMyQkVEMDM2RUJBRkEyNDhDMTM7dT0xNzMyMzg1MjQ4NDQ3MDkzNTg1O2g9MmZlZDc2M2EyNDA5NDFkMzIwYWIwYjI3ZThlYmExYWE=; tvoid=1; bltsr=1; user_display=563; _yasc=2xvlftNDZixh3JWMMTAAGeCgprMjSRqe/D5O+sz+USg0zxL17E9zLMzQXmTAy7BsF92BMrYAfh0NfQ==; bh=EjkiQ2hyb21pdW0iO3Y9IjEyOCIsICJOb3Q7QT1CcmFuZCI7dj0iMjQiLCAiT3BlcmEiO3Y9IjExNCIqAj8wOgkiV2luZG93cyJgh+uVugZqIdzK4f8IktihsQOfz+HqA/v68OcN6//99g+2xsyHCKWEAg==; yandexuid=1197179041732383499; yashr=4682342911732383504; yuidss=1197179041732383499; user_display=563",
    +   "Cookie": "i=dkim62pClrWWC4CShVQYMpVw1ELNVw4XJdL/lzT4E2r05IgcST1GtCA4ho/UyGgW2AO4qftDfZzGX2OHqCzwY7GUkpM=; spravka=dD0xNzMyNjgzMTEwO2k9MTgwLjI0OC41OS40MDtEPTkyOUM2MkQ0Mzc3OUNBMUFCNzg3NTIyMEQ4OEJBMEVBMzQ2RUNGNUU5Q0FEQUM5RUVDMTFCNjc1ODA2MThEQTQ3RTY3RTUyRUNBRDdBMTY2OTY1MjMzRDU1QjNGMTc1MDA0NDM3MjBGMUNGQTM5RjA3OUQwRjE2MzQxMUNFOTgxQ0E0RjNGRjRGODNCMEM1QjlGNTg5RkI4NDk0NEM2QjNDQUQ5NkJGRTBFNTVCQ0Y1OTEzMEY0O3U9MTczMjY4MzExMDY3MTA1MzIzNDtoPTA1YWJmMTY0ZmI2MGViNTBhMDUwZWUwMThmYWNiYjhm; yandexuid=1197179041732383499; yashr=4682342911732383504; yuidss=1197179041732383499; user_display=930",
      }

      51 |
      52 | it('can generate valid request headers', () => {
    > 53 |   expect(request.headers).toMatchObject({
         |                           ^
      54 |     Cookie:
      55 |       'i=dkim62pClrWWC4CShVQYMpVw1ELNVw4XJdL/lzT4E2r05IgcST1GtCA4ho/UyGgW2AO4qftDfZzGX2OHqCzwY7GUkpM=; ' +
      56 |       'spravka=dD0xNzMyMzg1MjQ4O2k9MTgwLjI0Ny4yNDEuNzA7RD1DMjQ4OTYzRURBNEE1NjVEMjg0Rjc5MDQyNEYzMjdGRDVERTg0MkQ2ODBCOUNCREUwQjk4OEYzRThDREIwQjVBNTUwRjc1OTFCRkMwRTRBRTM3RDA4MjZCMDAyNzhDMjEwMUYzOTE0NEQ5NjhBNjJGNENDRTYwM0ZDQUY4QjBBRTA0NDRGNjNENTQ0OUQ5MzkxMTdFRTMyQkVEMDM2RUJBRkEyNDhDMTM7dT0xNzMyMzg1MjQ4NDQ3MDkzNTg1O2g9MmZlZDc2M2EyNDA5NDFkMzIwYWIwYjI3ZThlYmExYWE=; tvoid=1; bltsr=1; user_display=563; _yasc=2xvlftNDZixh3JWMMTAAGeCgprMjSRqe/D5O+sz+USg0zxL17E9zLMzQXmTAy7BsF92BMrYAfh0NfQ==; bh=EjkiQ2hyb21pdW0iO3Y9IjEyOCIsICJOb3Q7QT1CcmFuZCI7dj0iMjQiLCAiT3BlcmEiO3Y9IjExNCIqAj8wOgkiV2luZG93cyJgh+uVugZqIdzK4f8IktihsQOfz+HqA/v68OcN6//99g+2xsyHCKWEAg==; ' +

      at Object.<anonymous> (sites/tv.yandex.ru/tv.yandex.ru.test.js:53:27)

  ● can parse response

    TypeError: Cannot read properties of undefined (reading 'then')

      188 |         if (workers.length === 0) {
      189 |           clearInterval(interval)
    > 190 |           resolve()
          |         ^
      191 |         }
      192 |       }, 500)
      193 |     })

      at doRequest (sites/tv.yandex.ru/tv.yandex.ru.config.js:190:9)
      at worker (sites/tv.yandex.ru/tv.yandex.ru.config.js:174:11)
      at sites/tv.yandex.ru/tv.yandex.ru.config.js:177:15

  ● can parse response

    thrown: "Exceeded timeout of 10000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      62 | })
      63 |
    > 64 | it('can parse response', async () => {
         | ^
      65 |   const content = fs.readFileSync(path.resolve(__dirname, '__data__/content.html'))
      66 |   const result = (
      67 |     await parser({ content, date, channel })

      at Object.<anonymous> (sites/tv.yandex.ru/tv.yandex.ru.test.js:64:1)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        13.288 s
Ran all test suites matching /tv.yandex.ru/i.
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

2024-12-01 21:40 UTC, freearhey approved these changes

2024-12-02 14:26 UTC, BellezaEmporium reviewed
Was removing the channels.xml file a mistake or intentional ?

2024-12-02 14:27 UTC, BellezaEmporium approved these changes
Whoops. GH sometimes gives bad hints.

2024-12-02 14:27 UTC, merged