Update tvplus.com.tr guide.
iptv-org/epg pull request #2508
Opened 2024-12-15 15:53 UTC by tohenk

Test:

```sh
npm test -- tvplus.com.tr

> test
> run-script-os tvplus.com.tr

> test:win32
> SET "TZ=Pacific/Nauru" && npx jest --runInBand tvplus.com.tr

 PASS  sites/tvplus.com.tr/tvplus.com.tr.test.js
  √ can generate valid url (4 ms)
  √ can parse response (15 ms)
  √ can handle empty guide

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        3.648 s, estimated 4 s
Ran all test suites matching /tvplus.com.tr/i.
```

Grab:

```sh
npm run grab -- --site=tvplus.com.tr

> grab
> npx tsx scripts/commands/epg/grab.ts --site=tvplus.com.tr

starting...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: tvplus.com.tr
loading channels...
  found 10 channel(s)
run #1:
  [1/20] tvplus.com.tr (tr) - 24TV.tr - Dec 15, 2024 (22 programs)
  [2/20] tvplus.com.tr (tr) - 24TV.tr - Dec 16, 2024 (19 programs)
  [3/20] tvplus.com.tr (tr) - BabyTV.uk - Dec 16, 2024 (48 programs)
  [4/20] tvplus.com.tr (tr) - BabyTV.uk - Dec 15, 2024 (48 programs)
  [5/20] tvplus.com.tr (tr) - ASpor.tr - Dec 16, 2024 (13 programs)
  [6/20] tvplus.com.tr (tr) - ASpor.tr - Dec 15, 2024 (14 programs)
  [7/20] tvplus.com.tr (tr) - APara.tr - Dec 16, 2024 (31 programs)
  [8/20] tvplus.com.tr (tr) - APara.tr - Dec 15, 2024 (25 programs)
  [9/20] tvplus.com.tr (tr) - AlJazeeraEnglish.qa - Dec 16, 2024 (32 programs)
  [10/20] tvplus.com.tr (tr) - AlJazeeraEnglish.qa - Dec 15, 2024 (32 programs)
  [11/20] tvplus.com.tr (tr) - AlJazeera.qa - Dec 16, 2024 (40 programs)
  [12/20] tvplus.com.tr (tr) - AlJazeera.qa - Dec 15, 2024 (41 programs)
  [13/20] tvplus.com.tr (tr) - AkitTV.tr - Dec 16, 2024 (15 programs)
  [14/20] tvplus.com.tr (tr) - AkitTV.tr - Dec 15, 2024 (12 programs)
  [15/20] tvplus.com.tr (tr) - AHaber.tr - Dec 16, 2024 (27 programs)
  [16/20] tvplus.com.tr (tr) - AHaber.tr - Dec 15, 2024 (19 programs)
  [17/20] tvplus.com.tr (tr) - A2TV.tr - Dec 16, 2024 (11 programs)
  [18/20] tvplus.com.tr (tr) - A2TV.tr - Dec 15, 2024 (11 programs)
  [19/20] tvplus.com.tr (tr) - 360.tr - Dec 16, 2024 (18 programs)
  [20/20] tvplus.com.tr (tr) - 360.tr - Dec 15, 2024 (18 programs)
  saving to "guide.xml"...
  done in 00h 02m 17s
```

Close #2305, #2377.

2024-12-16 11:45 UTC, BellezaEmporium commented
Test isn't viable to me, as the NextJS build ID will change anytime they push an update to their website.

2024-12-16 22:03 UTC, freearhey approved these changes

2024-12-17 02:23 UTC, freearhey requested changes
Now it's returning a 404 error:

```sh
npm run grab -- --site=tvplus.com.tr

> grab
> npx tsx scripts/commands/epg/grab.ts --site=tvplus.com.tr

starting...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: tvplus.com.tr
loading channels...
  found 144 channel(s)
run #1:
  [1/288] tvplus.com.tr (tr) - wOhzpck_jO2kKrDfRHmHs/blutv-play-1/4300 - Dec 17, 2024 (0 programs)
    ERR: Request failed with status code 404
  [2/288] tvplus.com.tr (tr) - wOhzpck_jO2kKrDfRHmHs/blutv-play-1/4300 - Dec 18, 2024 (0 programs)
    ERR: Request failed with status code 404
  [3/288] tvplus.com.tr (tr) - ViasatHistory.tr - Dec 18, 2024 (0 programs)
    ERR: Request failed with status code 404
  [4/288] tvplus.com.tr (tr) - ViasatHistory.tr - Dec 17, 2024 (0 programs)
    ERR: Request failed with status code 404
  [5/288] tvplus.com.tr (tr) - ViasatExplore.tr - Dec 18, 2024 (0 programs)
    ERR: Request failed with status code 404
  [6/288] tvplus.com.tr (tr) - ViasatExplore.tr - Dec 17, 2024 (0 programs)
    ERR: Request failed with status code 404
```

2024-12-17 03:04 UTC, tohenk commented
@freearhey  Can you try with new git clone, I've just force-pushed the branch.

```sh
npm run grab -- --site=tvplus.com.tr

> grab
> npx tsx scripts/commands/epg/grab.ts --site=tvplus.com.tr

starting...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: tvplus.com.tr
loading channels...
  found 143 channel(s)
run #1:
  site:tvplus.com.tr Got build id kUzvz_bbQJNaShlFUkrR3 +0ms
  [1/286] tvplus.com.tr (tr) - blutv-play-1/4300 - Dec 17, 2024 (28 programs)
  [2/286] tvplus.com.tr (tr) - blutv-play-1/4300 - Dec 18, 2024 (28 programs)
  [3/286] tvplus.com.tr (tr) - ViasatHistory.tr - Dec 18, 2024 (24 programs)
  [4/286] tvplus.com.tr (tr) - ViasatHistory.tr - Dec 17, 2024 (25 programs)
  [5/286] tvplus.com.tr (tr) - ViasatExplore.tr - Dec 18, 2024 (25 programs)
  [6/286] tvplus.com.tr (tr) - ViasatExplore.tr - Dec 17, 2024 (26 programs)
  [7/286] tvplus.com.tr (tr) - VavTV.tr - Dec 18, 2024 (23 programs)
  [8/286] tvplus.com.tr (tr) - VavTV.tr - Dec 17, 2024 (21 programs)
  [9/286] tvplus.com.tr (tr) - UlusalKanal.tr - Dec 18, 2024 (7 programs)
  [10/286] tvplus.com.tr (tr) - UlusalKanal.tr - Dec 17, 2024 (7 programs)
  [11/286] tvplus.com.tr (tr) - UlkeTV.tr - Dec 18, 2024 (7 programs)
  [12/286] tvplus.com.tr (tr) - UlkeTV.tr - Dec 17, 2024 (7 programs)
  [13/286] tvplus.com.tr (tr) - TVNET.tr - Dec 18, 2024 (35 programs)
  [14/286] tvplus.com.tr (tr) - TVNET.tr - Dec 17, 2024 (37 programs)
  [15/286] tvplus.com.tr (tr) - TV100.tr - Dec 18, 2024 (13 programs)
  [16/286] tvplus.com.tr (tr) - TV100.tr - Dec 17, 2024 (15 programs)
  [17/286] tvplus.com.tr (tr) - TV85.tr - Dec 18, 2024 (6 programs)
  [18/286] tvplus.com.tr (tr) - TV85.tr - Dec 17, 2024 (19 programs)
  [19/286] tvplus.com.tr (tr) - TV8.tr - Dec 18, 2024 (10 programs)
  [20/286] tvplus.com.tr (tr) - TV8.tr - Dec 17, 2024 (10 programs)
```

2024-12-17 17:08 UTC, freearhey approved these changes

2024-12-17 19:13 UTC, merged