Distinguish between UK and IE channels.
iptv-org/epg pull request #2521
Opened 2024-12-18 13:08 UTC by tohenk

- Update some channels TVG-ID.
- Fix duplicated TVG-ID between UK and IE.

2024-12-18 17:20 UTC, BellezaEmporium approved these changes
LGTM.

2024-12-18 19:14 UTC, freearhey requested changes
The thing is that in order for the changes to work all Irish variants must first be added to our [iptv-org/database](https://github.com/iptv-org/database), otherwise `xmltv_id` will be simply ignored in the program generation process.

2024-12-31 10:30 UTC, freearhey commented
I've added the missing channels to the database: https://github.com/iptv-org/database/pull/15106

2024-12-31 10:30 UTC, freearhey approved these changes

2024-12-31 10:30 UTC, merged