Pluto.tv
iptv-org/epg pull request #2554
Opened 2024-12-28 21:12 UTC by Newbiect

This is my contribution to the community.

2024-12-29 02:41 UTC, freearhey requested changes
Please rename the channel list files to match the rest of the sites: 
`pluto.tv.<CODE>.channels.xml > pluto.tv_<CODE>.channels.xml`

It would also be good to add a `readme.md` file.

Lastly, we use `xmltv-id` to load channel logos and link guides to channels in playlists. In order for this to work these IDs must first be added to our [iptv-org/database](https://github.com/iptv-org/database).

2024-12-29 03:56 UTC, Newbiect commented
I don't understand, this is how it is. pluto.tv.ar.channels.xml is like mi.tv mi.tv_ar.channels.xml or do I also have to put pluto.tv_ar.channels.xml?
readme.md ok.
xmltv-id I did what I could with what I had, there are too many channels and all 100% functional, I put them there to help, it's something I don't have time for so sorry.

2024-12-29 11:26 UTC, freearhey commented
All you need to do is change the period in the file name to an underscore to make it look like this: 
`<SITE-DOMAIN>_<COUNTRY-CODE>.channels.xml`

2024-12-30 01:19 UTC, freearhey submitted a review, later dismissed

2024-12-31 07:30 UTC, tohenk requested changes
Remove semicolon to follow coding standard.

2024-12-31 13:52 UTC, Newbiect commented
> Remove semicolon to follow coding standard.

Excuse my ignorance, but where?

2024-12-31 17:12 UTC, tohenk commented
> > Remove semicolon to follow coding standard.
> 
> Excuse my ignorance, but where?

Remove all semicolons in [pluto.tv.config.js](https://github.com/iptv-org/epg/pull/2554/commits/c1add314720076ba61179204de67b1a1a25338dc).

2025-01-01 06:21 UTC, freearhey requested changes
> Remove all semicolons in [pluto.tv.config.js](https://github.com/iptv-org/epg/pull/2554/commits/c1add314720076ba61179204de67b1a1a25338dc).

Well, then it's worth updating `pluto.tv.test.js` as well.

2025-01-01 17:36 UTC, freearhey submitted a review, later dismissed

2025-01-02 01:51 UTC, tohenk requested changes

2025-01-02 01:51 UTC, tohenk commented on sites/pluto.tv/readme.md
> +npm test --- pluto.tv
Add missing closing code block after Line 12.

2025-01-02 02:29 UTC, tohenk approved these changes

2025-01-02 12:43 UTC, freearhey approved these changes

2025-01-02 12:44 UTC, merged