Update mncvision.id_id.channels.xml
iptv-org/epg pull request #526
Opened 2022-02-19 03:39 UTC by F640

- Added Galaxy, Galaxy Premium, IMC, SPOTV, SPOTV 2, BeIN Sports 3 Indonesia, FOX News Channel, Al Quran Al Kareem, MNC Sports 2, and MNC Sports 3
- Removed non-existent channel in this schedule (Star Chinese Movies South East Asia and BeIN Sports 2 Indonesia)

2022-02-19 07:37 UTC, freearhey requested changes
Some of the channels have the wrong `xmltv-id`: https://github.com/iptv-org/epg/runs/5257411962?check_suite_focus=true

The correct IDs can be found here: https://iptv-org.github.io/

2022-02-19 07:51 UTC, F640 commented
There is no proper xmltv_id for these invalid channels, but it is in mncvision channel list.

2022-02-19 10:16 UTC, freearhey commented
If a channel is not on the list you can add it yourself via [iptv-org/database](https://github.com/iptv-org/database)

2022-02-20 09:02 UTC, freearhey approved these changes

2022-02-20 09:02 UTC, merged