Update tvtv.us_us.channels.xml
iptv-org/epg pull request #618
Opened 2022-03-12 10:55 UTC by Central302

Re-try 3, Add ION Television Philadelphia and 3 Internet Channels.

2022-03-12 22:28 UTC, freearhey requested changes

2022-03-12 22:28 UTC, freearhey commented on sites/tvtv.us/tvtv.us_us.channels.xml
> +    <channel lang="en" xmltv_id="PlutoTVBlackNewsChannel.us" site_id="116018">BNCGO (Pluto)/channel>
```suggestion
    <channel lang="en" xmltv_id="PlutoTVBlackNewsChannel.us" site_id="116018">BNCGO (Pluto)</channel>
```

2022-03-12 22:28 UTC, freearhey commented on sites/tvtv.us/tvtv.us_us.channels.xml
> +    <channel lang="en" xmltv_id="SkyNewsInternational.uk" site_id="114448">Sky News for US Streaming/channel>
```suggestion
    <channel lang="en" xmltv_id="SkyNewsInternational.uk" site_id="114448">Sky News for US Streaming</channel>
```

2022-03-12 22:28 UTC, freearhey commented on sites/tvtv.us/tvtv.us_us.channels.xml
> +    <channel lang="en" xmltv_id="WPPXDT6.us" site_id="83522">Defy TV (WPPX-DT6) Philadelphia PA/channel>
```suggestion
    <channel lang="en" xmltv_id="WPPXDT1.us" site_id="43971">Ion Television (WPPX-DT1) Philadelphia PA</channel>
    <channel lang="en" xmltv_id="WPPXDT2.us" site_id="43973">Bounce (WPPX-DT2) Philadelphia PA</channel>
    <channel lang="en" xmltv_id="WPPXDT3.us" site_id="43975">Grit (WPPX-DT3) Philadelphia PA</channel>
    <channel lang="en" xmltv_id="WPPXDT4.us" site_id="43977">Truereal (WPPX-DT4) Philadelphia PA</channel>
    <channel lang="en" xmltv_id="WPPXDT5.us" site_id="82712">Laff (WPPX-DT5) Philadelphia PA</channel>
    <channel lang="en" xmltv_id="WPPXDT6.us" site_id="83522">Defy TV (WPPX-DT6) Philadelphia PA</channel>
```

2022-03-13 03:59 UTC, Central302 commented
Thanks for Suggest @freearhey !

2022-03-13 12:01 UTC, freearhey approved these changes

2022-03-13 12:01 UTC, merged