Update tvtv.us_us-local.channels.xml
iptv-org/epg pull request #822
Opened 2022-06-03 16:45 UTC by TheDeatCrusher

2022-06-04 00:42 UTC, freearhey requested changes
Also please make sure that the `xmltv_id` of the channels is the same as here: https://iptv-org.github.io

2022-06-04 00:42 UTC, freearhey commented on sites/tvtv.us/tvtv.us_us-local.channels.xml
> +    <channel lang="en" xmltv_id="WTNZ.us" site_id="11602">FOX (WTNZ) KNOXVILLE</channeL>
```suggestion
    <channel lang="en" xmltv_id="WTNZ.us" site_id="11602">FOX (WTNZ) KNOXVILLE</channel>
```

2022-06-04 00:42 UTC, freearhey commented on sites/tvtv.us/tvtv.us_us-local.channels.xml
> +    <channel lang="en" xmltv_id="WBIR.us" site_id="11305">NBC (WBIR) KNOXVILLE</channeL>
```suggestion
    <channel lang="en" xmltv_id="WBIR.us" site_id="11305">NBC (WBIR) KNOXVILLE</channel>
```

2022-06-04 16:37 UTC, TheDeatCrusher commented on sites/tvtv.us/tvtv.us_us-local.channels.xml
> +    <channel lang="en" xmltv_id="WTNZ.us" site_id="11602">FOX (WTNZ) KNOXVILLE</channeL>
I made another commit and fixed it

2022-06-05 10:00 UTC, freearhey requested changes

2022-06-05 10:00 UTC, freearhey commented on sites/tvtv.us/tvtv.us_us-local.channels.xml
> +    <channel lang="en" xmltv_id="WTNZDT1.us" site_id="11602">FOX (WTNZ) KNOXVILLE</channeL>
```suggestion
    <channel lang="en" xmltv_id="WTNZDT1.us" site_id="11602">FOX (WTNZ) KNOXVILLE</channel>
```

2022-06-05 10:00 UTC, freearhey commented on sites/tvtv.us/tvtv.us_us-local.channels.xml
> +    <channel lang="en" xmltv_id="WBIRDT1.us" site_id="11305">NBC (WBIR) KNOXVILLE</channeL>
```suggestion
    <channel lang="en" xmltv_id="WBIRDT1.us" site_id="11305">NBC (WBIR) KNOXVILLE</channel>
```

2022-06-16 23:03 UTC, freearhey approved these changes

2022-06-16 23:03 UTC, merged